name: Push component to https://components.espressif.com
on:
  push:
    tags:
      - '*'

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: 'udp_server'
          namespace: 'larryli'
          version: ${{ github.ref_name }}
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
